# Generated by Django 4.1.6 on 2023-03-22 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo2', '0002_tasks_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='user',
        ),
    ]
