# Generated by Django 4.1.6 on 2023-03-23 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo2', '0003_remove_tasks_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
